Arista:
  eos: switch
Aruba:
  cx: switch
Check Point:
  gaia: firewall
Cisco:
  (catelyst|c\d+): switch
  (nexus|n\d+k): switch
  asa: firewall
  isr: router
  asr: router
Fortinet:
  fortigate: firewall
Hillstone:
  sg: firewall
Huawei:
  usg: firewall
  ce: switch
  netengine: router
  ar: router
  s: switch
Paloalto:
  pa: firewall
Juniper:
  srx: firewall
  qfx: switch
  ex: switch
  mx: router
H3C:
  secpath: firewall
  sr: router
  (v|s): switch