# Vendor keyed SNMP parse rules.

Fortinet:
  rules:
    - oid: "1.3.6.1.2.1.47.1.1.1.1.10.1"
      template: |
        Value MODEL (\S+)
        Value VERSION ([Vv][\d\.]+)

        Start
          ^${MODEL} ${VERSION} -> Record
Aruba:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (\S+)
        Value VERSION (\S+)

        Start
          ^.+ ${MODEL} ${VERSION}$$ -> Record
Huawei:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (.+)
        Value VERSION (\S+)

        Start
          ^.+[Vv]ersion.* \(${MODEL} ${VERSION}\) -> Record
          ^.+[Vv]ersion.* ${MODEL} ${VERSION} -> Record
Check Point:
  rules:
    - oid: "1.3.6.1.2.1.25.6.3.1.2.118"
      template: |
        Value MODEL (gaia)

        Start
          ^${MODEL} -> Record
    - oid: "1.3.6.1.2.1.25.6.3.1.2.310"
      template: |
        Value VERSION (R.+)

        Start
          ^.*${VERSION} -> Record
Hillstone:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (\S+)

        Start
          ^.+ ${MODEL} -> Record
    - oid: "1.3.6.1.4.1.28557.2.2.1.2.0"
      template: |
        Value VERSION (\S+)

        Start
          ^[Vv]ersion ${VERSION} -> Record
Juniper:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (\S+)
        Value VERSION (\S+)

        Start
          ^.+ Inc. ${MODEL} .+ JUNOS ${VERSION}, -> Record
Cisco:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (\S+)
        Value VERSION (\S+)

        Start
          ^Cisco IOS Software, ${MODEL} .+ Version ${VERSION},  -> Record
H3C:
  rules:
    - oid: "1.3.6.1.2.1.1.1.0"
      template: |
        Value MODEL (.+)
        Value VERSION (\S+)

        Start
          ^.+Version ${VERSION},
          ^H3C ${MODEL} -> Record
