# Vendor keyed SSH parse rules.
Arista:
  command: "show version"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)
    Value SERIAL (\S+)

    Start
      ^Arista\s+${MODEL}
      ^[Ss]oftware image version:\s*${VERSION}
      ^[Ss]erial number:\s*${SERIAL}
      ^${HOSTNAME}(>|#) -> Record
Aruba:
  command: "show system"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)
    Value SERIAL (\S+)

    Start
      ^[Hh]ostname\s*:\s*${HOSTNAME}
      ^[Pp]roduct [Nn]ame\s*:\s*\S*\s*${MODEL}
      ^\S*\s*[Ss]erial [Nn]br\s*:\s*${SERIAL}
      ^\S*\s*[Vv]ersion\s*:\s*${VERSION} -> Record
Check Point:
  command: "show version all"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)

    Start
      ^[Pp]roduct [Vv]ersion Check Point ${MODEL} ${VERSION}
      ^${HOSTNAME}> -> Record
Cisco:
  command: "show version"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (.+)
    Value VERSION (\S+)
    Value SERIAL (\S+)

    Start
      ^.*Software Version ${VERSION}
      ^Model Id:\s*${MODEL}
      ^[Ss]erial [Nn]umber: ${SERIAL}
      ^\s*[Cc]isco ${MODEL} Chassis
      ^\s*NXOS: version ${VERSION}
      ^\s*Processor Board ID ${SERIAL}
      ^${HOSTNAME}(>|#) -> Record
Fortinet:
  command: "get system status"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION ([Vv\d\.]+)
    Value SERIAL (\S+)

    Start
      ^[Vv]ersion: ${MODEL} ${VERSION},
      ^[Ss]erial-[Nn]umber: ${SERIAL}
      ^[Hh]ostname: ${HOSTNAME} -> Record
Hillstone:
  command: "show version"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)
    Value SERIAL (\S+)

    Start
      ^.+[Ss]oftware, [Vv]ersion ${VERSION}
      ^[Pp]roduct name: ${MODEL} S/N: ${SERIAL}
      ^${HOSTNAME}# -> Record
Huawei:
  command: "display version"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)
                            
    Start
      ^.+[Ss]oftware, [Vv]ersion \S+ \(${MODEL} ${VERSION}\)
      ^<${HOSTNAME}> -> Record
Paloalto:
  command: "show system info"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)
    Value SERIAL (\S+)

    Start
      ^hostname: ${HOSTNAME}
      ^model: ${MODEL}
      ^serial: ${SERIAL}
      ^sw-version: ${VERSION} -> Record
Juniper:
  command: "show version"
  template: |
    Value HOSTNAME (\S+)
    Value MODEL (\S+)
    Value VERSION (\S+)

    Start
      ^Hostname: ${HOSTNAME}
      ^Model: ${MODEL}
      ^Junos: ${VERSION} -> Record
